spring.application.name=CUSTOMER-SERVICE
server.port=8081

# Cấu hình Eureka Client kết nối tới Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Khoảng thời gian gửi heartbeat và gia hạn đăng ký (giây)
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=20
