spring.application.name=discovery-server
server.port=8761

# Eureka Server không cần tự đăng ký chính nó
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Tắt chế độ bảo vệ (Self Preservation) để dễ quan sát khi thực hành Lab
eureka.server.enable-self-preservation=false

# Thời gian quét định kỳ để loại bỏ các service không gửi heartbeat (ms)
eureka.server.eviction-interval-timer-in-ms=5000
